/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as HeatmapsRouteImport } from './routes/heatmaps'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as HeatmapTemplateIdRouteImport } from './routes/heatmap.$templateId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapsRoute = HeatmapsRouteImport.update({
  id: '/heatmaps',
  path: '/heatmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapTemplateIdRoute = HeatmapTemplateIdRouteImport.update({
  id: '/heatmap/$templateId',
  path: '/heatmap/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/heatmaps': typeof HeatmapsRoute
  '/scan': typeof ScanRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/heatmap/$templateId': typeof HeatmapTemplateIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/heatmaps': typeof HeatmapsRoute
  '/scan': typeof ScanRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/heatmap/$templateId': typeof HeatmapTemplateIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/heatmaps': typeof HeatmapsRoute
  '/scan': typeof ScanRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/heatmap/$templateId': typeof HeatmapTemplateIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/heatmaps'
    | '/scan'
    | '/sessions'
    | '/settings'
    | '/heatmap/$templateId'
    | '/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/heatmaps'
    | '/scan'
    | '/sessions'
    | '/settings'
    | '/heatmap/$templateId'
    | '/session/$id'
  id:
    | '__root__'
    | '/'
    | '/heatmaps'
    | '/scan'
    | '/sessions'
    | '/settings'
    | '/heatmap/$templateId'
    | '/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeatmapsRoute: typeof HeatmapsRoute
  ScanRoute: typeof ScanRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  HeatmapTemplateIdRoute: typeof HeatmapTemplateIdRoute
  SessionIdRoute: typeof SessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmaps': {
      id: '/heatmaps'
      path: '/heatmaps'
      fullPath: '/heatmaps'
      preLoaderRoute: typeof HeatmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap/$templateId': {
      id: '/heatmap/$templateId'
      path: '/heatmap/$templateId'
      fullPath: '/heatmap/$templateId'
      preLoaderRoute: typeof HeatmapTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeatmapsRoute: HeatmapsRoute,
  ScanRoute: ScanRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  HeatmapTemplateIdRoute: HeatmapTemplateIdRoute,
  SessionIdRoute: SessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
